### ISSUE TITLE
Exception while invoking method 'increasePostViews' Error: Match error: Expected string, got object

### ISSUE THREAD

**Issue by queso** [TelescopeJS/Telescope#1103]
After upgrade to 0.22.2, it appears that I am getting this error in the logs.

**Comment by SachaG** [comment]
Should be fixed, hopefully.

**Comment by cloudunicorn** [comment]
Is this fix going to master branch?

**Comment by cloudunicorn** [comment]
This didn't fix it for me. On the site I see: 
<img width="663" alt="screenshot 2015-08-13 13 05 46" src="https://cloud.githubusercontent.com/assets/5987576/9260364/148a09f0-41bc-11e5-9cbb-7bb09d63639f.png">

**Comment by queso** [comment]
@cloudunicorn I am not sure your issue is related to mine. You are seeing an iron router error, my error was from a DDP call failing behind the scenes.

**Comment by cloudunicorn** [comment]
hm, my logs say: Exception while invoking method 'increasePostViews' Error: Match error: Expected string, got object

**Comment by cloudunicorn** [comment]
My app works fine on local, but shows that error live on the site / digital ocean.

**Comment by cloudunicorn** [comment]
hm, new error now, i'll stop hijacking this.

Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.

**Comment by milezteg** [comment]
I don't think the fix worked as I am also getting this error with the latest Telescope Devel and latest Zeiss.  Full error code:

`I20150813-07:32:09.226(-6)? Exception while invoking method 'increasePostViews' Error: Match error: Expected string, got object
I20150813-07:32:09.226(-6)?     at checkSubtree (packages/check/match.js:159:1)
I20150813-07:32:09.227(-6)?     at check (packages/check/match.js:32:1)
I20150813-07:32:09.227(-6)?     at [object Object].Meteor.methods.increasePostViews (packages/telescope:posts/lib/methods.js:283:1)
I20150813-07:32:09.227(-6)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
I20150813-07:32:09.227(-6)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150813-07:32:09.227(-6)?     at packages/ddp/livedata_server.js:648:1
I20150813-07:32:09.227(-6)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150813-07:32:09.227(-6)?     at packages/ddp/livedata_server.js:647:1
I20150813-07:32:09.227(-6)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150813-07:32:09.227(-6)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150813-07:32:09.227(-6)? Sanitized and reported to the client as: Match failed [400]
I20150813-07:32:09.227(-6)?`

**Comment by SachaG** [comment]
@cloudunicorn yeah the error discussed here and the Fiber thing don't actually crash your app or have any effect on the site, so your issue must be different. 

@milezteg the code should now match anything, so it's weird that you're still getting an error. Are you 100% sure you're running the latest devel?

https://github.com/TelescopeJS/Telescope/commit/65efb6180cac6688f66278a976e4852ab47acf1f

**Comment by milezteg** [comment]
>>Are you 100% sure you're running the latest devel?

Doh!  Missed that last commit.  Error is gone and increasePostViews working as expected.

Thanks Sacha =)
